version: '3.8'

services:
  db-mysql:
    image: mysql
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"

  c_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: c_client
    # stdin_open: true
    # tty: true
    depends_on:
      - db-mysql

  c_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: c_server
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql
      
